version: "3.10"

services:
  frontend:
    build: frontend/
    ports:
      - 8501:8501
    networks:
      - deploy_network
    depends_on:
      - backend
    volumes:
        - ./frontend:/app
    container_name: streamlit    

  backend:
    build: backend/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    volumes:
      - ./backend:/app
    container_name: fastapi

networks:
  deploy_network:
    driver: bridge