version: "3.10"

services:
  backend:
    platform: linux/amd64  
    build: backend
    image: essai.azurecr.io/backend
    container_name: fastapi
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 8000:8000

  frontend:
    platform: linux/amd64
    build: ./frontend
    image: essai.azurecr.io/frontend 
    container_name: streamlit
    environment:
      BACKEND: backend  
    ports:
          - 80:80
